repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.3.0  # Use your desired version
    hooks:
      - id: black
        types: [python]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
