repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.3.0
    hooks:
      - id: black
        types: [python]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/opensource-nepal/commitlint
    rev: v1.2.0
    hooks:
      - id: commitlint
