name: Commitlint

on:
  pull_request:

jobs:
  commitlint:
    runs-on: ubuntu-latest
    name: Commitlint
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run commitlint
        uses: opensource-nepal/commitlint@v1
